# Generated by Django 3.2.7 on 2021-09-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_accessrecord_topic_webpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
